### ISSUE TITLE
?discord Command Request

### ISSUE THREAD

**Issue by Auxillarus** [carsakiller/Carsas-Commands#4]
**Is your feature request related to a problem? Please describe.**
-No problem, just would be a nice feature.
**Describe the feature you'd like**
Pretty self explanatory, simply run "?discord" in chat and have it display a client-side message of a configurable discord invite
**Additional context**
Ex:
?discord
[Server] discord.gg/#######

P.S: I'm new to GitHub, apologies if I've made any mistakes.

**Comment by carsakiller** [comment]
Hello 👋. This sounds like a pretty easy feature to add. Have they added the ability to the game to copy text from the in-game chat? I have not played Stormworks since February so I don't know what changes they have made. If they haven't, that will definitely be a factor as to if I add the feature or not.

**Comment by Dargino** [comment]
> Hello 👋. This sounds like a pretty easy feature to add. Have they added the ability to the game to copy text from the in-game chat? I have not played Stormworks since February so I don't know what changes they have made. If they haven't, that will definitely be a factor as to if I add the feature or not.

I can confirm that the ability to copy text from the ingame chat window is not currently in the game no matter how much we'd like it to be..
